### ISSUE TITLE
Request for Broadcast date and Time to be included in output and...

### ISSUE THREAD

**Issue by Sav0ia** [truethug/YouNow_Downloader-mac-linux#2]
Thanks for making this great script :) 
Would it be possible to have the output file include Broadcast date and time?  I tried to add to the script but screwed it up XD still learning.

Also  a neat feature would be to check existing files and not overwrite them when batch downloading missing or incomplete files.

Thanks :D

**Comment by truethug** [comment]
Hey,

Are you able to get the json file? I don't have a working link. I will
gladly update the code if you can help me there.

Thanks

**Comment by Sav0ia** [comment]
Hello truethug :)
The json file? For what sorry?

**Comment by truethug** [comment]
On line 86 there is a command:

**Comment by truethug** [comment]
Looks like I was doing something wrong. I added the broadcast date if it's a previous broadcast and the current date if it's live
