### ISSUE TITLE
Unable to list past broadcasts

### ISSUE THREAD

**Issue by Sav0ia** [truethug/YouNow_Downloader-mac-linux#4]
Thanks for the brilliant script :) Not sure if it's an API change but past broadcasts are not being listed :(

Thanks!

**Comment by truethug** [comment]
@Sav0ia It is working for me. Try on a different computer. The admins are notorious for banning people (at least temporarily).

**Comment by Sav0ia** [comment]
> @Sav0ia It is working for me. Try on a different computer. The admins are notorious for banning people (at least temporarily).
> 

Thanks truethug for the reply!

New broadcasts that end are listed (such as the other day etc)
But users who have not broadcasted in a while have no listing at all or option to download.
I'll give you 2 examples to try

Broadcast showing -> User:  Mat.i
Broadcast not showing(broadcasted early last year) -> User: karinasarinana__

I used another script to verify past broadcasts and they showed up on the other script but could not be downloaded.

Thanks!

**Comment by truethug** [comment]
I specifically don't list broadcasts that are unavailable for download.

**Comment by Sav0ia** [comment]
Sorry then truethug and thank you for the hard work :)

Is there a way you'll be able to retrieve those unavailable downloads?

**Comment by truethug** [comment]
Unfortunately they are unavailable.

**Comment by Sav0ia** [comment]
Damn :( did they move the files to another server or changed some directory? Will there be future access?
