### ISSUE TITLE
Can't view past broadcasts as of March 15th

### ISSUE THREAD

**Issue by ZarthJ** [truethug/YouNow_Downloader-mac-linux#5]
Just yesterday it was working fine, now I do not see any old broadcasts listed. Tried multiple IPs and computers. Has it been killed?

**Comment by truethug** [comment]
Looks like they changed the api server again. Keep an eye out for an update

**Comment by truethug** [comment]
@ZarthJ I mostly translated this from a Windows batch script. Some people have helped me find the API in the past but I haven't seen anything new there.

**Comment by Sav0ia** [comment]
@truethug Has there been any update on the new API buddy? Thanks

**Comment by truethug** [comment]
No, I get permission denied. I think authentication is necessary

**Comment by Sav0ia** [comment]
@truethug  Damnit.

I saw this, would this help?

https://www.reddit.com/r/YouNow/comments/60ljkt/any_downloaders_actually_work/

**Comment by truethug** [comment]
Thanks. I'll do a quick test and see if I can't get this working.

**Comment by Sav0ia** [comment]
@truethug Appreciate it, best of luck!

**Comment by truethug** [comment]
Didn't work on the first try. I'll look into this tomorrow. Cheers

**Comment by Sav0ia** [comment]
No prob, hoping it can work :)

**Comment by truethug** [comment]
this is quick and messy but works. I will clean it up. I also need to look into broadcasts that don't have moments

**Comment by truethug** [comment]
Still needs cleanup, but can now download past broadcasts

**Comment by Sav0ia** [comment]
@truethug Thanks for the fix, testing it now and it works :) 
Noticed though some broadcasts show up but are no longer available. A user I tested had broadcasts from October but perhaps the file is no longer on their server.

Thanks :)

**Comment by truethug** [comment]
Yeah I was getting that from the old API call. I didn't see that
information when I was updating. I'll take another look when I have a
minute.
